[package]
name = "glass-mu1603"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty-hex = "0.4.1"
rusb = "0.9.3"

glass-common = { path = "../glass-common" }
